apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ubuntu-mic-prometheus-exporter
    release: prometheus-operator
  name: ubuntu-mic-prometheus-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: prometheus-client
    scrapeTimeout: 25s
  jobLabel: name
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app : ubuntu-mic-prometheus-exporter
